import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { validateConfig, digest, targetNames, publicTarget, mailboxProvider } from './config.mjs';
import { renderTemplates } from './template.mjs';
import { aws as command, assertIdentity } from './aws.mjs';
import { buildPackage } from './package.mjs';
import { createMailtmClient } from './mailtm.mjs';
import { primaryApply, primaryRollback } from './primary.mjs';
import { recoverFailedStack, isRecoveryStack, assertRecoveryStack } from './recovery.mjs';
import { authorizationTransaction } from './cumulative.mjs';
import { privateDirectory } from './private-directory.mjs';
const delay=ms=>new Promise(r=>globalThis.setTimeout(r,ms));
const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
function run(args,env={}){const r=spawnSync(args[0],args.slice(1),{cwd:root,encoding:'utf8',env:{...process.env,...env},maxBuffer:10*1024*1024});if(r.status!==0)throw new Error('SETUP_BUILD_FAILED');return r.stdout.trim();}
function outputs(stack){return Object.fromEntries((stack.Outputs??[]).map(item=>[item.OutputKey,item.OutputValue]));}
export function installationPlan(raw,manifest){const c=validateConfig(raw);if(manifest.sourceCommit!==c.sourceCommit)throw new Error('SOURCE_COMMIT_MISMATCH');for(const name of ['api','broker'])if(!/^[0-9a-f]{64}$/.test(manifest.artifacts?.[name]?.sha256??''))throw new Error('ARTIFACT_HASH_MISSING');return {config:c,names:targetNames(c),templates:renderTemplates(c,{apiKey:manifest.artifacts.api.sha256+'/api.zip',brokerKey:manifest.artifacts.broker.sha256+'/broker.zip'}),sourceCommit:c.sourceCommit,authorizationApproved:c.authorization.approved,primaryRollout:c.primaryRollout};}
function describe(aws,name){try{return aws('cloudformation','describe-stacks',{StackName:name}).Stacks[0];}catch(e){if(e.missing)return null;throw e;}}
function assertOwned(stack){if(stack&&!isRecoveryStack(stack)&&!(stack.Tags??[]).some(t=>t.Key==='KnownEnoughQa'&&t.Value==='true'))throw new Error('EXISTING_STACK_NOT_OWNED');}
export function mailboxGuard(c,active,zone,records,existing){if(zone.HostedZone?.Config?.PrivateZone===true)throw new Error('PUBLIC_MAIL_ZONE_REQUIRED');if(active.RuleSet?.Name&&active.RuleSet.Name!=='known-enough-qa')throw new Error('ACTIVE_SES_RULE_SET_CONFLICT');const name=zone.HostedZone.Name.replace(/\.$/,'');if(c.mailDomain!==name&&!c.mailDomain.endsWith('.'+name))throw new Error('MAIL_DOMAIN_ZONE_MISMATCH');if(!existing&&records.ResourceRecordSets?.some(r=>r.Type==='MX'&&r.Name.replace(/\.$/,'')===c.mailDomain))throw new Error('EXISTING_MX_CONFLICT');}
async function deployStack(aws,name,template,parameters){const existing=describe(aws,name);assertOwned(existing);const input={StackName:name,TemplateBody:JSON.stringify(template),Parameters:parameters,Capabilities:['CAPABILITY_NAMED_IAM'],Tags:[{Key:'KnownEnoughQa',Value:'true'}]};if(existing){try{aws('cloudformation','update-stack',input);}catch(e){if(!e.noUpdates)throw e;return existing;}}else aws('cloudformation','create-stack',{...input,OnFailure:'ROLLBACK'});for(let i=0;i<180;i++){const s=describe(aws,name);if(['CREATE_COMPLETE','UPDATE_COMPLETE'].includes(s?.StackStatus))return s;if(s?.StackStatus?.includes('FAILED')||s?.StackStatus?.includes('ROLLBACK'))throw new Error('STACK_SETUP_FAILED');await delay(5000);}throw new Error('STACK_SETUP_TIMEOUT');}
export function verifyRuntime(target,manifest,observed){if(target.Account!=='092954139775'||target.Region!=='us-east-1'||target.SourceCommit!==manifest.sourceCommit)throw new Error('INSTALLED_TARGET_MISMATCH');for(const name of ['api','broker']){const c=observed[name];if(c.State!=='Active'||c.LastUpdateStatus!=='Successful'||c.CodeSha256!==Buffer.from(manifest.artifacts[name].sha256,'hex').toString('base64'))throw new Error('INSTALLED_CODE_MISMATCH');}const e=observed.api.Environment?.Variables;if(e?.NP_GROUP_TABLE_NAME!==target.GroupTable||e?.KE13B_TABLE_NAME!==target.DecisionTable||e?.QA_CONTROL_TABLE!==target.ControlTable||e?.COGNITO_USER_POOL_ID!==target.PoolId||e?.COGNITO_PARTICIPANT_CLIENT_ID!==target.ParticipantClientId||e?.COGNITO_DISPLAY_CLIENT_ID!==target.DisplayClientId||e?.QA_SOURCE_COMMIT!==manifest.sourceCommit||e?.NP_GROUPS_ENABLED!=='true')throw new Error('INSTALLED_CONFIG_MISMATCH');if(target.MailboxProvider&&observed.broker.Environment?.Variables?.QA_MAIL_PROVIDER!==target.MailboxProvider)throw new Error('MAILBOX_PROVIDER_READBACK_FAILED');return true;}
export async function webArtifact(target,directory){run(['npm','run','build'],{VITE_COGNITO_REGION:target.Region,VITE_COGNITO_USER_POOL_ID:target.PoolId,VITE_COGNITO_DOMAIN:target.CognitoDomain,VITE_COGNITO_PARTICIPANT_CLIENT_ID:target.ParticipantClientId,VITE_COGNITO_DISPLAY_CLIENT_ID:target.DisplayClientId,VITE_API_BASE_URL:target.ApiUrl});run(['python3','-c',"import zipfile,pathlib,sys; d=pathlib.Path(sys.argv[1]); z=zipfile.ZipFile(sys.argv[2],'w',zipfile.ZIP_DEFLATED,compresslevel=9); [(lambda i,p: (setattr(i,'compress_type',zipfile.ZIP_DEFLATED),setattr(i,'external_attr',0o100644<<16),z.writestr(i,p.read_bytes())))(zipfile.ZipInfo(str(p.relative_to(d)),(2026,10,1,0,0,0)),p) for p in sorted(d.rglob('*')) if p.is_file()]; z.close()",root+'/apps/web/dist',directory+'/web.zip']);return digest(readFileSync(directory+'/web.zip'));}
export async function publishWeb(aws,target,directory){const deployment=aws('amplify','create-deployment',{appId:target.AmplifyAppId,branchName:'main'});const uploaded=await globalThis.fetch(deployment.zipUploadUrl,{method:'PUT',body:readFileSync(directory+'/web.zip'),redirect:'error'});if(!uploaded.ok)throw new Error('WEB_UPLOAD_FAILED');aws('amplify','start-deployment',{appId:target.AmplifyAppId,branchName:'main',jobId:deployment.jobId});for(let i=0;i<120;i++){const j=aws('amplify','get-job',{appId:target.AmplifyAppId,branchName:'main',jobId:deployment.jobId}).job.summary;if(['SUCCEED','SUCCEEDED'].includes(j.status))return String(deployment.jobId);if(['FAILED','CANCELLED'].includes(j.status))throw new Error('WEB_DEPLOYMENT_FAILED');await delay(5000);}throw new Error('WEB_DEPLOYMENT_TIMEOUT');}
export async function install(mode,raw,directory,aws=command){const c=validateConfig(raw);const dir=privateDirectory(directory,root);if(!['dry-run','validate','recover','resume','apply','readback','rollback'].includes(mode))throw new Error('INVALID_MODE');if(run(['git','rev-parse','HEAD'])!==c.sourceCommit||run(['git','status','--porcelain','--untracked-files=no']))throw new Error('CLEAN_PINNED_SOURCE_REQUIRED');const manifest=await buildPackage(dir,c.sourceCommit);const plan=installationPlan(c,manifest);writeFileSync(dir+'/core.json',JSON.stringify(plan.templates.core,null,2),{mode:0o600});writeFileSync(dir+'/mail.json',JSON.stringify(plan.templates.mail,null,2),{mode:0o600});if(mode==='dry-run')return {status:'PREPARED',sourceCommit:c.sourceCommit,artifacts:manifest.artifacts,cloudWrites:false};assertIdentity(aws('sts','get-caller-identity'),c);
  if(mode==='resume'){const current=describe(aws,c.stack);assertOwned(current);if(!current||isRecoveryStack(current)||current.StackStatus==='ROLLBACK_COMPLETE')await recoverFailedStack(c,plan.templates.core,dir,aws);return install('apply',raw,dir,aws);}
  if(mode==='recover')return recoverFailedStack(c,plan.templates.core,dir,aws);
  const names=plan.names;const mailName=c.stack+'-mail';const core=describe(aws,c.stack),mail=describe(aws,mailName);assertOwned(core);assertOwned(mail);
  const freeMail=mailboxProvider(c)==='mailtm';
  if(core?.StackStatus==='ROLLBACK_COMPLETE')throw new Error('RETAINED_TABLE_RECOVERY_REQUIRED');
  const imported=isRecoveryStack(core);
  if(imported){const template=aws('cloudformation','get-template',{StackName:core.StackId}).TemplateBody;const summaries=aws('cloudformation','list-stack-resources',{StackName:core.StackId}).StackResourceSummaries.filter(item=>item.ResourceStatus!=='DELETE_COMPLETE');assertRecoveryStack(c,core,summaries,typeof template==='string'?JSON.parse(template):template,plan.templates.core);}
  if(freeMail){if(mail || (core&&!imported&&outputs(core).MailboxProvider!=='mailtm'))throw new Error('MAILBOX_PROVIDER_MIGRATION_REQUIRED'); if(mode==='validate'||mode==='apply')await createMailtmClient().domain();}
  else {if(core&&outputs(core).MailboxProvider==='mailtm')throw new Error('MAILBOX_PROVIDER_MIGRATION_REQUIRED');const active=aws('ses','describe-active-receipt-rule-set');mailboxGuard(c,active,aws('route53','get-hosted-zone',{Id:c.hostedZoneId}),aws('route53','list-resource-record-sets',{HostedZoneId:c.hostedZoneId}),mail);}
  if(mode==='validate')return {status:'VALIDATED',sourceCommit:c.sourceCommit,cloudWrites:false};
  if(mode==='rollback'){if(core){const target=publicTarget(outputs(core));const lease=aws('dynamodb','get-item',{TableName:target.ControlTable,Key:{PK:{S:'LEASE'},SK:{S:'STATE'}},ConsistentRead:true});if(lease.Item&&JSON.parse(lease.Item.payload.S).status!=='CLEAN')throw new Error('CLEANUP_REQUIRED_BEFORE_ROLLBACK');const prior=aws('dynamodb','get-item',{TableName:target.ControlTable,Key:{PK:{S:'AUTH'},SK:{S:'STATE'}},ConsistentRead:true});if(prior.Item){const a=JSON.parse(prior.Item.payload.S);aws('dynamodb','put-item',{TableName:target.ControlTable,Item:{PK:{S:'AUTH'},SK:{S:'STATE'},payload:{S:JSON.stringify({...a,approved:false})},version:{N:String(Number(prior.Item.version.N)+1)}},ConditionExpression:'#v=:v',ExpressionAttributeNames:{'#v':'version'},ExpressionAttributeValues:{':v':prior.Item.version}});}for(const role of ['KnownEnoughGithubQaTest','KnownEnoughGithubQaRelease'])aws('iam','delete-role-policy',{RoleName:role,PolicyName:role.endsWith('Test')?'InvokeFixtureBrokerAndOwnLogins':'ExactQaRelease'});}if(core&&outputs(core).PrimaryReleaseRoleArn==='arn:aws:iam::092954139775:role/KnownEnoughGithubPrimaryRelease')aws('iam','delete-role-policy',{RoleName:'KnownEnoughGithubPrimaryRelease',PolicyName:'ExactPrimaryCodeOnly'});if(existsSync(dir+'/primary-private-journal.json'))await primaryRollback(dir,aws);return {status:'REVOKED',resources:'RETAINED_FOR_FORWARD_REPAIR'};}
  if(mode==='apply'){
    if(core){const controlTable=imported?names.control:publicTarget(outputs(core)).ControlTable;const lease=aws('dynamodb','get-item',{TableName:controlTable,Key:{PK:{S:'LEASE'},SK:{S:'STATE'}},ConsistentRead:true});if(lease.Item&&JSON.parse(lease.Item.payload.S).status!=='CLEAN')throw new Error('ACTIVE_LEASE_SETUP_BLOCKED');}
    const logging=aws('bedrock','get-model-invocation-logging-configuration').loggingConfig;if(logging&&Object.entries(logging).some(([key,value])=>key.endsWith('DataDeliveryEnabled')&&value===true))throw new Error('MODEL_INVOCATION_LOGGING_ENABLED');
    if(!c.authorization.approved||Date.parse(c.authorization.expiresAt)<=Date.now())throw new Error('CONCRETE_SETUP_AND_RECURRING_AUTHORIZATION_REQUIRED');
    if(!core){for(const name of [names.decisions,names.groups,names.control]){try{aws('dynamodb','describe-table',{TableName:name});throw new Error('EXISTING_TABLE_NOT_STACK_OWNED');}catch(e){if(!e.missing)throw e;}}}
    try{aws('s3api','head-bucket',{Bucket:names.artifacts,ExpectedBucketOwner:c.account});const tags=aws('s3api','get-bucket-tagging',{Bucket:names.artifacts});if(!tags.TagSet.some(t=>t.Key==='KnownEnoughQa'&&t.Value==='true'))throw new Error('ARTIFACT_BUCKET_NOT_OWNED');}catch(e){if(!e.missing)throw e;aws('s3api','create-bucket',{Bucket:names.artifacts});aws('s3api','put-bucket-tagging',{Bucket:names.artifacts,Tagging:{TagSet:[{Key:'KnownEnoughQa',Value:'true'}]}});aws('s3api','put-public-access-block',{Bucket:names.artifacts,PublicAccessBlockConfiguration:{BlockPublicAcls:true,IgnorePublicAcls:true,BlockPublicPolicy:true,RestrictPublicBuckets:true}});aws('s3api','put-bucket-encryption',{Bucket:names.artifacts,ServerSideEncryptionConfiguration:{Rules:[{ApplyServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]}});}
    for(const name of ['api','broker'])aws('s3api','put-object',{Bucket:names.artifacts,Key:manifest.artifacts[name].sha256+'/'+name+'.zip',Body:dir+'/'+name+'.zip',ChecksumSHA256:Buffer.from(manifest.artifacts[name].sha256,'hex').toString('base64')});
    let m={};
    if(!freeMail){m=outputs(await deployStack(aws,mailName,plan.templates.mail,[]));aws('ses','set-active-receipt-rule-set',{RuleSetName:'known-enough-qa'});
    let verified=false;for(let i=0;i<120;i++){const identity=aws('sesv2','get-email-identity',{EmailIdentity:c.mailDomain});if(identity.VerifiedForSendingStatus){verified=true;break;}await delay(5000);}if(!verified)throw new Error('MAIL_IDENTITY_NOT_VERIFIED_RETRY_APPLY');}

    const parameters=[...(!freeMail?[{ParameterKey:'MailboxBucket',ParameterValue:m.MailboxBucket},{ParameterKey:'EmailSourceArn',ParameterValue:m.EmailSourceArn}]:[]),core?.Parameters?.some(p=>p.ParameterKey==='EmailKey')?{ParameterKey:'EmailKey',UsePreviousValue:true}:{ParameterKey:'EmailKey',ParameterValue:randomBytes(32).toString('hex')}];const installed=await deployStack(aws,c.stack,plan.templates.core,parameters);const target=publicTarget(outputs(installed));
    const key={PK:{S:'AUTH'},SK:{S:'STATE'}};const lease=aws('dynamodb','get-item',{TableName:target.ControlTable,Key:{PK:{S:'LEASE'},SK:{S:'STATE'}},ConsistentRead:true});if(lease.Item&&JSON.parse(lease.Item.payload.S).status!=='CLEAN')throw new Error('ACTIVE_LEASE_AUTHORIZATION_UPDATE_BLOCKED');const prior=aws('dynamodb','get-item',{TableName:target.ControlTable,Key:key,ConsistentRead:true});const total=aws('dynamodb','get-item',{TableName:target.ControlTable,Key:{PK:{S:'TOTAL'},SK:{S:'STATE'}},ConsistentRead:true});aws('dynamodb','transact-write-items',authorizationTransaction(target.ControlTable,prior.Item,lease.Item,total.Item,c.authorization));
    const webSha256=await webArtifact(target,dir);const jobId=await publishWeb(aws,target,dir);const primary=await primaryApply(c,manifest,dir,aws);writeFileSync(dir+'/installed-target.json',JSON.stringify({...target,artifacts:manifest.artifacts,webSha256,jobId,primary},null,2)+'\n',{mode:0o600});
  }
  const target=publicTarget(outputs(describe(aws,c.stack)??{}));const observed={api:aws('lambda','get-function-configuration',{FunctionName:target.ApiFunction}),broker:aws('lambda','get-function-configuration',{FunctionName:target.BrokerFunction})};verifyRuntime(target,manifest,observed);
  for(const name of [target.DecisionTable,target.GroupTable,target.ControlTable]){const t=aws('dynamodb','describe-table',{TableName:name}).Table;if(t.TableStatus!=='ACTIVE'||t.KeySchema.map(k=>k.AttributeName).sort().join()!=='PK,SK'||t.AttributeDefinitions.some(a=>a.AttributeType!=='S'))throw new Error('TABLE_READBACK_FAILED');}
  if(observed.broker.Environment?.Variables?.QA_MAIL_PROVIDER!==mailboxProvider(c)||target.MailboxProvider!==mailboxProvider(c))throw new Error('MAILBOX_PROVIDER_READBACK_FAILED');
  const pool=aws('cognito-idp','describe-user-pool',{UserPoolId:target.PoolId}).UserPool;const participant=aws('cognito-idp','describe-user-pool-client',{UserPoolId:target.PoolId,ClientId:target.ParticipantClientId}).UserPoolClient;if(pool.AdminCreateUserConfig.AllowAdminCreateUserOnly||!pool.AutoVerifiedAttributes.includes('email')||!participant.AllowedOAuthScopes.includes('email')||participant.ClientSecret)throw new Error('COGNITO_READBACK_FAILED');
  if(freeMail&&pool.EmailConfiguration?.EmailSendingAccount!=='COGNITO_DEFAULT')throw new Error('DEFAULT_EMAIL_READBACK_FAILED');
  return {status:'SETUP_READBACK_PASS',sourceCommit:c.sourceCommit,cloudQualification:'PENDING_LIVE04',targetFile:dir+'/installed-target.json'};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){try{console.log(JSON.stringify(await install(process.argv[2],JSON.parse(readFileSync(process.argv[3],'utf8')),process.argv[4])));}catch(error){console.error(JSON.stringify({status:'BLOCKED',code:error.message.match(/^(?:[A-Z0-9_]+|AWS_OPERATION_FAILED:[a-z0-9-]+:[a-z0-9-]+)$/)?error.message:'SETUP_OPERATION_FAILED',recovery:'Retry same pinned command/config and private directory; drift requires reviewed repair.'}));process.exitCode=1;}}
