import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { digest } from './config.mjs';
import { preservationInput, awsSkeleton } from './aws.mjs';
const functionName='known-enough-stage-api',pool='us-east-1_V9OMjd0zx',client='3accf7paalvon2m8ue8okfi853',api='u94iyvt6p9';
const routes=['GET /account','POST /account/register','GET /groups','POST /groups','POST /groups/accept','POST /groups/{groupId}/invitations','POST /groups/{groupId}/remove','GET /groups/{groupId}/drafts/{draftId}','POST /groups/{groupId}/drafts','POST /groups/{groupId}/drafts/{draftId}','POST /groups/{groupId}/drafts/{draftId}/create','GET /groups/{groupId}/decisions/{decisionId}/review','POST /groups/{groupId}/decisions/{decisionId}/revise','OPTIONS /account','OPTIONS /account/register','OPTIONS /groups','OPTIONS /groups/{proxy+}'];
export function primaryPlan(config,current){if(!config.primaryRollout)return {enabled:false};if(current.RevisionId!==config.primaryExpectedRevision||current.State!=='Active'||current.LastUpdateStatus!=='Successful'||current.Environment?.Variables?.KE14_MODEL_MODE!=='DISABLED')throw new Error('NP00_PRIMARY_HOLD_OR_REVISION_CHANGED');return {enabled:true,functionName,pool,client,api,groupTable:'KnownEnoughGroupsStage',routes};}
export async function primaryApply(config,manifest,directory,aws){
  const current=aws('lambda','get-function-configuration',{FunctionName:functionName});if(config.primaryRollout&&existsSync(directory+'/primary-private-journal.json')){const prior=JSON.parse(readFileSync(directory+'/primary-private-journal.json','utf8'));if(current.RevisionId===prior.afterRevision&&current.CodeSha256===Buffer.from(manifest.artifacts.api.sha256,'hex').toString('base64')&&current.Environment?.Variables?.NP_GROUPS_ENABLED==='true'&&current.Environment?.Variables?.KE14_MODEL_MODE==='DISABLED'&&current.LastUpdateStatus==='Successful')return {status:'PASS',codeSha256:manifest.artifacts.api.sha256};}const plan=primaryPlan(config,current);if(!plan.enabled)return {status:'NOT_RUN'};
  const p=aws('cognito-idp','describe-user-pool',{UserPoolId:pool}).UserPool;const c=aws('cognito-idp','describe-user-pool-client',{UserPoolId:pool,ClientId:client}).UserPoolClient;const beforeRoutes=aws('apigatewayv2','get-routes',{ApiId:api}).Items??[];
  const anchor=beforeRoutes.find(r=>r.RouteKey==='ANY /decisions/{proxy+}');if(!anchor?.AuthorizerId||!anchor.Target)throw new Error('PRIMARY_ROUTE_ANCHOR_MISSING');
  const snapshot={schemaVersion:1,config:current,pool:p,client:c,createdRoutes:[],createdPolicy:false,afterRevision:current.RevisionId,rollbackCode:null,poolAfter:p,clientAfter:c};
  const journal=directory+'/primary-private-journal.json';const save=()=>writeFileSync(journal,JSON.stringify(snapshot),{mode:0o600});save();
  const deployed=aws('lambda','get-function',{FunctionName:functionName});const response=await globalThis.fetch(deployed.Code.Location,{redirect:'error'});if(!response.ok)throw new Error('ROLLBACK_CODE_UNAVAILABLE');const prior=Buffer.from(await response.arrayBuffer());if(Buffer.from(digest(prior),'hex').toString('base64')!==current.CodeSha256)throw new Error('ROLLBACK_CODE_MISMATCH');writeFileSync(directory+'/primary-rollback.zip',prior,{mode:0o600});snapshot.rollbackCode=digest(prior);save();
  // Retain the newly created group table even on rollback; never replace primary decision storage.
  try{const table=aws('dynamodb','describe-table',{TableName:plan.groupTable}).Table;if(table.KeySchema?.map(k=>k.AttributeName).sort().join()!=='PK,SK')throw new Error('PRIMARY_TABLE_CONFLICT');}catch(error){if(!error.missing)throw error;aws('dynamodb','create-table',{TableName:plan.groupTable,BillingMode:'PAY_PER_REQUEST',AttributeDefinitions:[{AttributeName:'PK',AttributeType:'S'},{AttributeName:'SK',AttributeType:'S'}],KeySchema:[{AttributeName:'PK',KeyType:'HASH'},{AttributeName:'SK',KeyType:'RANGE'}],DeletionProtectionEnabled:true,SSESpecification:{Enabled:true},Tags:[{Key:'KnownEnoughPrimaryGroup',Value:'true'}]});for(let i=0;i<60;i++){if(aws('dynamodb','describe-table',{TableName:plan.groupTable}).Table.TableStatus==='ACTIVE')break;await new Promise(r=>globalThis.setTimeout(r,1000));if(i===59)throw new Error('PRIMARY_TABLE_TIMEOUT',{cause:error});}}
  const runtimeRole=current.Role.split('/').at(-1);const name='KnownEnoughStageGroups';const policy={Version:'2012-10-17',Statement:[{Effect:'Allow',Action:['dynamodb:GetItem','dynamodb:PutItem'],Condition:{'ForAllValues:StringEquals':{'dynamodb:LeadingKeys':['NP#GROUPS']}},Resource:`arn:aws:dynamodb:us-east-1:${config.account}:table/${plan.groupTable}`}]};
  try{const existing=aws('iam','get-role-policy',{RoleName:runtimeRole,PolicyName:name});const document=typeof existing.PolicyDocument==='string'?JSON.parse(decodeURIComponent(existing.PolicyDocument)):existing.PolicyDocument;if(digest(document)!==digest(policy))throw new Error('PRIMARY_POLICY_CONFLICT');}catch(error){if(!error.missing)throw error;aws('iam','put-role-policy',{RoleName:runtimeRole,PolicyName:name,PolicyDocument:JSON.stringify(policy)});snapshot.createdPolicy=true;save();}
  for(const route of routes){const found=beforeRoutes.find(r=>r.RouteKey===route);const isOptions=route.startsWith('OPTIONS ');const expected={ApiId:api,RouteKey:route,AuthorizationType:isOptions?'NONE':'JWT',...(isOptions?{}:{AuthorizerId:anchor.AuthorizerId}),Target:anchor.Target};if(found){if(found.AuthorizationType!==expected.AuthorizationType||found.Target!==expected.Target||(!isOptions&&found.AuthorizerId!==anchor.AuthorizerId))throw new Error('PRIMARY_ROUTE_CONFLICT');continue;}const created=aws('apigatewayv2','create-route',expected);snapshot.createdRoutes.push(created.RouteId);save();}
  const poolInput=preservationInput(p,awsSkeleton('cognito-idp','update-user-pool'));poolInput.UserPoolId=pool;poolInput.AdminCreateUserConfig={...p.AdminCreateUserConfig,AllowAdminCreateUserOnly:false};poolInput.AutoVerifiedAttributes=[...new Set([...(p.AutoVerifiedAttributes??[]),'email'])];if(digest(aws('cognito-idp','describe-user-pool',{UserPoolId:pool}).UserPool)!==digest(p))throw new Error('PRIMARY_POOL_DRIFT');aws('cognito-idp','update-user-pool',poolInput);snapshot.poolAfter=aws('cognito-idp','describe-user-pool',{UserPoolId:pool}).UserPool;save();
  const clientInput=preservationInput(c,awsSkeleton('cognito-idp','update-user-pool-client'));clientInput.UserPoolId=pool;clientInput.ClientId=client;clientInput.AllowedOAuthScopes=[...new Set([...(c.AllowedOAuthScopes??[]),'openid','email'])];if(digest(aws('cognito-idp','describe-user-pool-client',{UserPoolId:pool,ClientId:client}).UserPoolClient)!==digest(c))throw new Error('PRIMARY_CLIENT_DRIFT');aws('cognito-idp','update-user-pool-client',clientInput);snapshot.clientAfter=aws('cognito-idp','describe-user-pool-client',{UserPoolId:pool,ClientId:client}).UserPoolClient;save();
  const next={...current.Environment.Variables,NP_GROUPS_ENABLED:'true',NP_GROUP_TABLE_NAME:plan.groupTable,NP_GROUP_EMAIL_KEY:current.Environment.Variables.NP_GROUP_EMAIL_KEY??randomBytes(32).toString('hex'),NP_COGNITO_DOMAIN:'https://known-enough-092954139775.auth.us-east-1.amazoncognito.com'};
  const code=aws('lambda','update-function-code',{FunctionName:functionName,RevisionId:current.RevisionId,ZipFile:readFileSync(directory+'/api.zip').toString('base64')});snapshot.afterRevision=code.RevisionId;save();
  // The installer waits for update completion before applying the preserved full environment.
  for(let i=0;i<60;i++){const live=aws('lambda','get-function-configuration',{FunctionName:functionName});if(live.LastUpdateStatus==='Failed')throw new Error('PRIMARY_UPDATE_FAILED');if(live.LastUpdateStatus==='Successful'){if(live.CodeSha256!==Buffer.from(manifest.artifacts.api.sha256,'hex').toString('base64'))throw new Error('PRIMARY_CODE_MISMATCH');const changed=aws('lambda','update-function-configuration',{FunctionName:functionName,RevisionId:live.RevisionId,Environment:{Variables:next},Handler:'api.handler'});snapshot.afterRevision=changed.RevisionId;save();for(let j=0;j<60;j++){const ready=aws('lambda','get-function-configuration',{FunctionName:functionName});if(ready.LastUpdateStatus==='Failed')throw new Error('PRIMARY_CONFIG_FAILED');if(ready.LastUpdateStatus==='Successful'){if(digest(ready.Environment.Variables)!==digest(next)||ready.Handler!=='api.handler')throw new Error('PRIMARY_CONFIG_MISMATCH');snapshot.afterRevision=ready.RevisionId;save();return {status:'PASS',codeSha256:manifest.artifacts.api.sha256};}await new Promise(r=>globalThis.setTimeout(r,1000));}throw new Error('PRIMARY_CONFIG_TIMEOUT');}await new Promise(r=>globalThis.setTimeout(r,1000));}throw new Error('PRIMARY_UPDATE_TIMEOUT');
}
export async function primaryRollback(directory,aws){const s=JSON.parse(readFileSync(directory+'/primary-private-journal.json','utf8'));const current=aws('lambda','get-function-configuration',{FunctionName:functionName});if(current.RevisionId!==s.afterRevision)throw new Error('PRIMARY_ROLLBACK_REVISION_CHANGED');if(digest(aws('cognito-idp','describe-user-pool',{UserPoolId:pool}).UserPool)!==digest(s.poolAfter)||digest(aws('cognito-idp','describe-user-pool-client',{UserPoolId:pool,ClientId:client}).UserPoolClient)!==digest(s.clientAfter))throw new Error('PRIMARY_COGNITO_DRIFT');const code=readFileSync(directory+'/primary-rollback.zip');if(digest(code)!==s.rollbackCode)throw new Error('ROLLBACK_BYTES_CHANGED');aws('lambda','update-function-code',{FunctionName:functionName,RevisionId:current.RevisionId,ZipFile:code.toString('base64')});for(let i=0;i<60;i++){const ready=aws('lambda','get-function-configuration',{FunctionName:functionName});if(ready.LastUpdateStatus==='Successful'){aws('lambda','update-function-configuration',{FunctionName:functionName,RevisionId:ready.RevisionId,Environment:s.config.Environment,Handler:s.config.Handler});break;}await new Promise(r=>globalThis.setTimeout(r,1000));}
  for(const id of s.createdRoutes)aws('apigatewayv2','delete-route',{ApiId:api,RouteId:id});
  if(s.createdPolicy)aws('iam','delete-role-policy',{RoleName:s.config.Role.split('/').at(-1),PolicyName:'KnownEnoughStageGroups'});
  if(s.poolAfter&&digest(aws('cognito-idp','describe-user-pool',{UserPoolId:pool}).UserPool)!==digest(s.poolAfter))throw new Error('PRIMARY_POOL_DRIFT');if(s.clientAfter&&digest(aws('cognito-idp','describe-user-pool-client',{UserPoolId:pool,ClientId:client}).UserPoolClient)!==digest(s.clientAfter))throw new Error('PRIMARY_CLIENT_DRIFT');const p=preservationInput(s.pool,awsSkeleton('cognito-idp','update-user-pool'));p.UserPoolId=pool;aws('cognito-idp','update-user-pool',p);const c=preservationInput(s.client,awsSkeleton('cognito-idp','update-user-pool-client'));c.UserPoolId=pool;c.ClientId=client;aws('cognito-idp','update-user-pool-client',c);return {status:'PASS',groupTable:'RETAINED'};
}
