import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

export const PRIMARY_SIGNUP_TARGET = Object.freeze({
    account: '092954139775', region: 'us-east-1', pool: 'us-east-1_V9OMjd0zx',
    client: '3accf7paalvon2m8ue8okfi853', actor: '143764700'
});
const phases = ['PREPARED', 'SIGNUP_INTENT', 'SIGNUP_UNKNOWN', 'CREATED', 'CONFIRM_INTENT',
    'CONFIRMED', 'LOGIN_INTENT', 'VERIFIED', 'CLEANUP_INTENT', 'CLEANUP_UNKNOWN', 'CLEAN', 'BLOCKED'];
const results = ['PASS', 'FAIL', 'UNKNOWN', 'BLOCKED'];
const cleanups = ['CLEAN', 'UNKNOWN', 'BLOCKED', 'NOT_NEEDED'];
const counters = ['signupAttempts', 'mailReads', 'confirmationAttempts', 'loginAttempts', 'deleteAttempts'];
class DriverFault extends Error {}
const fail = code => { throw new DriverFault(code); };
const exact = (value, keys) => value && typeof value === 'object' && !Array.isArray(value)
    && Object.keys(value).length === keys.length && keys.every(key => Object.hasOwn(value, key));
const hex = (value, length) => typeof value === 'string' && new RegExp(`^[a-f0-9]{${length}}$`).test(value);
const safeToken = value => typeof value === 'string' && /^[a-zA-Z0-9_-]{16,128}$/.test(value);
const subjectValid = value => typeof value === 'string'
    && /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(value);

// Nonces/owner tokens must be freshly generated by the trusted runtime. No live
// adapter is installed here; caller-supplied claims alone are not live evidence.
export function primarySignupPlan(input) {
    if (!exact(input, ['runId', 'sourceSha', 'nonce', 'ownerToken']) || !hex(input.runId, 16)
        || !hex(input.sourceSha, 40) || !hex(input.nonce, 32) || !hex(input.ownerToken, 32)) fail('PRIMARY_PLAN_REJECTED');
    const plan = { ...input, username: `ke-primary-${input.runId}-${input.nonce}` };
    return Object.freeze({ ...plan, binding: createHash('sha256').update(JSON.stringify(plan)).digest('hex') });
}

function checkedPlan(plan) {
    if (!exact(plan, ['runId', 'sourceSha', 'nonce', 'ownerToken', 'username', 'binding'])) fail('PRIMARY_PLAN_REJECTED');
    const checked = primarySignupPlan({ runId: plan.runId, sourceSha: plan.sourceSha, nonce: plan.nonce, ownerToken: plan.ownerToken });
    if (checked.binding !== plan.binding || checked.username !== plan.username) fail('PRIMARY_PLAN_REJECTED');
    return checked;
}

function recordFor(plan, record) {
    if (!exact(record, ['revision', 'binding', 'phase', 'subject', 'lease', 'result', 'cleanup', ...counters])
        || !Number.isSafeInteger(record.revision) || record.revision < 0 || record.binding !== plan.binding
        || !phases.includes(record.phase) || !results.includes(record.result) || !cleanups.includes(record.cleanup)
        || !(record.subject === null || subjectValid(record.subject))
        || !exact(record.lease, ['id', 'username', 'mailboxKey']) || !safeToken(record.lease.id)
        || record.lease.username !== plan.username || !safeToken(record.lease.mailboxKey)
        || counters.some(key => !Number.isSafeInteger(record[key]) || record[key] < 0 || record[key] > (key === 'mailReads' ? 3 : 1))) fail('PRIMARY_JOURNAL_REJECTED');
    if ((record.phase === 'PREPARED' && (counters.some(key => record[key] !== 0) || record.subject !== null
            || record.result !== 'UNKNOWN' || record.cleanup !== 'NOT_NEEDED'))
        || (record.signupAttempts === 0 && !['PREPARED', 'BLOCKED'].includes(record.phase))
        || (record.subject === null && !['PREPARED', 'BLOCKED', 'SIGNUP_INTENT', 'SIGNUP_UNKNOWN'].includes(record.phase))
        || (record.subject !== null && !record.signupAttempts)
        || (record.loginAttempts && (!record.confirmationAttempts || !record.mailReads))
        || (record.result === 'PASS' && (!record.subject || !record.loginAttempts
            || !['VERIFIED', 'CLEANUP_INTENT', 'CLEANUP_UNKNOWN', 'CLEAN', 'BLOCKED'].includes(record.phase)))
        || ((record.phase === 'CLEAN') !== (record.cleanup === 'CLEAN'))
        || (record.deleteAttempts && !['CLEANUP_INTENT', 'CLEANUP_UNKNOWN', 'CLEAN'].includes(record.phase))) fail('PRIMARY_JOURNAL_REJECTED');
    return structuredClone(record);
}

export function primarySignupReport(record) {
    // Explicit allowlist: no journal spreads, resource identifiers, subject,
    // fixture, raw provider error, password, mailbox or authentication material.
    const report = { status: record?.result === 'PASS' && record?.cleanup === 'CLEAN' && record?.phase === 'CLEAN'
            && record?.signupAttempts === 1 && record?.confirmationAttempts === 1 && record?.loginAttempts === 1
            && Number.isSafeInteger(record?.mailReads) && record.mailReads >= 1 && record.mailReads <= 3 ? 'PASS' : 'BLOCKED_OR_FAILED',
        execution: results.includes(record?.result) ? record.result : 'UNKNOWN',
        cleanup: cleanups.includes(record?.cleanup) ? record.cleanup : 'UNKNOWN',
        phase: phases.includes(record?.phase) ? record.phase : 'BLOCKED' };
    for (const key of counters) report[key] = Number.isSafeInteger(record?.[key]) && record[key] >= 0
        && record[key] <= (key === 'mailReads' ? 3 : 1) ? record[key] : 0;
    return report;
}

/** Private durable atomic storage and trusted bounded service ports are required.
 * No port is substituted with a local mock by this module. Port exceptions stay
 * private; an uncertain write never becomes a successful write or a retry.
 */
export function primarySignupDriver({ journal, ports }) {
    for (const method of ['read', 'createIfAbsent', 'compareAndSwap']) {
        if (typeof journal?.[method] !== 'function') fail('PRIMARY_JOURNAL_REQUIRED');
    }
    for (const method of ['verifyContext', 'verifyLease', 'lookupSubject', 'signup', 'readMail', 'confirm', 'login', 'deleteSubject']) {
        if (typeof ports?.[method] !== 'function') fail('PRIMARY_PORT_REQUIRED');
    }
    async function bounded(action, unavailable) {
        const signal = globalThis.AbortSignal.timeout(30_000);
        // Deadline ends observation, not the external request. A late write is
        // ambiguous and its persisted intent remains fenced against retries.
        return await new Promise((resolve, reject) => {
            const abort = () => reject(new DriverFault(unavailable));
            if (signal.aborted) return abort();
            signal.addEventListener('abort', abort, { once: true });
            Promise.resolve().then(() => action(signal)).then(value => {
                signal.removeEventListener('abort', abort); resolve(value);
            }, () => {
                signal.removeEventListener('abort', abort); reject(new DriverFault(unavailable));
            });
        });
    }
    const service = (method, input) => bounded(signal => ports[method](input, { signal }), 'PRIMARY_PORT_UNKNOWN');
    async function context(plan) {
        const proof = await service('verifyContext', plan);
        if (!proof || Object.entries(PRIMARY_SIGNUP_TARGET).some(([key, value]) => proof[key] !== value)
            || proof.sourceSha !== plan.sourceSha || proof.cleanupBinding !== 'IMMUTABLE_SUBJECT'
            || proof.partialCleanup !== 'VERIFIED' || proof.exclusiveLease !== 'VERIFIED'
            || proof.journalDurability !== 'VERIFIED' || proof.passwordPolicy !== 'MIN8_ALL_CLASSES'
            || proof.publicSignup !== 'VERIFIED') fail('PRIMARY_CONTEXT_REJECTED');
    }
    async function load(plan) {
        return recordFor(plan, await bounded(() => journal.read(plan.runId), 'PRIMARY_JOURNAL_UNAVAILABLE'));
    }
    async function advance(plan, current, patch) {
        const next = recordFor(plan, { ...current, ...patch, revision: current.revision + 1 });
        const updated = await bounded(() => journal.compareAndSwap(plan.runId, current.revision, next), 'PRIMARY_JOURNAL_UNAVAILABLE');
        if (updated === false) fail('PRIMARY_JOURNAL_CONFLICT');
        if (updated !== true) fail('PRIMARY_JOURNAL_UNAVAILABLE');
        return next;
    }
    async function lease(plan, expected) {
        const proof = await service('verifyLease', plan);
        if (!exact(proof, ['id', 'username', 'mailboxKey']) || !safeToken(proof.id) || !safeToken(proof.mailboxKey)
            || proof.username !== plan.username || (expected && Object.keys(expected).some(key => proof[key] !== expected[key]))) fail('PRIMARY_LEASE_REJECTED');
        return proof;
    }
    async function lookup(plan, current) {
        const found = await service('lookupSubject', { plan, lease: current.lease, subject: current.subject });
        // Absence cannot carry a subject, username, error or partial result.
        // Require a closed observation before it can authorize create or CLEAN.
        const absent = exact(found, ['status']) && found.status === 'ABSENT';
        const present = exact(found, ['status', 'subject', 'username']) && found.status === 'PRESENT'
            && subjectValid(found.subject) && found.username === plan.username;
        if (!absent && !present) fail('PRIMARY_LOOKUP_UNKNOWN');
        return found;
    }
    async function cleanup(plan, current) {
        // Subjectless/ambiguous signup cannot safely be recovered by username.
        if (!current.subject) return current;
        try {
            await context(plan);
            await lease(plan, current.lease);
            const found = await lookup(plan, current);
            if (found.status === 'ABSENT') return await advance(plan, current, { phase: 'CLEAN', cleanup: 'CLEAN' });
            if (found.subject !== current.subject) return await advance(plan, current, { phase: 'BLOCKED', cleanup: 'BLOCKED' });
            // CAS before the destructive action fences concurrent/replayed cleanup.
            current = await advance(plan, current, { phase: 'CLEANUP_INTENT', deleteAttempts: 1, cleanup: 'UNKNOWN' });
            try {
                await service('deleteSubject', { plan, lease: current.lease, subject: current.subject });
            } catch { /* Readback may establish completion after a lost response. */ }
            const after = await lookup(plan, current);
            return await advance(plan, current, after.status === 'ABSENT'
                ? { phase: 'CLEAN', cleanup: 'CLEAN' } : { phase: 'CLEANUP_UNKNOWN', cleanup: 'UNKNOWN' });
        } catch (error) {
            if (error instanceof DriverFault && ['PRIMARY_JOURNAL_CONFLICT', 'PRIMARY_JOURNAL_UNAVAILABLE'].includes(error.message)) throw error;
            return await advance(plan, current, { phase: 'CLEANUP_UNKNOWN', cleanup: 'UNKNOWN' });
        }
    }
    return Object.freeze({
        async prepare(input) {
            const plan = checkedPlan(input);
            await context(plan);
            const fixture = await lease(plan);
            const initial = { revision: 0, binding: plan.binding, phase: 'PREPARED', subject: null, lease: fixture,
                result: 'UNKNOWN', cleanup: 'NOT_NEEDED', signupAttempts: 0, mailReads: 0,
                confirmationAttempts: 0, loginAttempts: 0, deleteAttempts: 0 };
            // Immutable run key: conflicting nonce/source/owner cannot replace it.
            const created = await bounded(() => journal.createIfAbsent(plan.runId, initial), 'PRIMARY_JOURNAL_UNAVAILABLE');
            if (created !== true && created !== false) fail('PRIMARY_JOURNAL_UNAVAILABLE');
            return primarySignupReport(await load(plan));
        },
        async execute(input) {
            const plan = checkedPlan(input);
            let current = await load(plan);
            if (current.phase !== 'PREPARED') return primarySignupReport(current);
            // All failure-capable preflight reads precede signup intent and mutation.
            await context(plan);
            await lease(plan, current.lease);
            if ((await lookup(plan, current)).status !== 'ABSENT') {
                current = await advance(plan, current, { phase: 'BLOCKED', result: 'BLOCKED' });
                return primarySignupReport(current);
            }
            current = await advance(plan, current, { phase: 'SIGNUP_INTENT', signupAttempts: 1, cleanup: 'UNKNOWN' });
            let created;
            try { created = await service('signup', { plan, lease: current.lease }); }
            catch { /* No second signup; lost response may have created an account. */ }
            if (!created || !subjectValid(created.subject)) {
                current = await advance(plan, current, { phase: 'SIGNUP_UNKNOWN', result: 'UNKNOWN' });
                return primarySignupReport(current);
            }
            current = await advance(plan, current, { phase: 'CREATED', subject: created.subject, result: 'FAIL' });
            try {
                const observed = await lookup(plan, current);
                if (observed.status !== 'PRESENT' || observed.subject !== current.subject) fail('PRIMARY_SUBJECT_REJECTED');
                let mail;
                while (current.mailReads < 3 && !mail) {
                    current = await advance(plan, current, { mailReads: current.mailReads + 1 });
                    const response = await service('readMail', { plan, lease: current.lease });
                    if (response?.status === 'READY' && response.leaseId === current.lease.id
                        && response.mailboxKey === current.lease.mailboxKey && /^\d{6}$/.test(response.code)) mail = response;
                    else if (response?.status !== 'EMPTY') fail('PRIMARY_MAIL_REJECTED');
                }
                if (!mail) fail('PRIMARY_MAIL_UNKNOWN');
                current = await advance(plan, current, { phase: 'CONFIRM_INTENT', confirmationAttempts: 1 });
                const confirmation = await service('confirm', { plan, lease: current.lease, subject: current.subject, code: mail.code });
                if (confirmation?.status !== 'CONFIRMED') fail('PRIMARY_CONFIRM_UNKNOWN');
                current = await advance(plan, current, { phase: 'CONFIRMED' });
                current = await advance(plan, current, { phase: 'LOGIN_INTENT', loginAttempts: 1 });
                const authenticated = await service('login', { plan, lease: current.lease });
                // Trusted login port verifies signatures, issuer, audience, expiry,
                // PKCE/state/nonce and server identity; decoded claims are insufficient.
                if (authenticated?.status !== 'VERIFIED' || authenticated.subject !== current.subject
                    || authenticated.pool !== PRIMARY_SIGNUP_TARGET.pool || authenticated.client !== PRIMARY_SIGNUP_TARGET.client
                    || authenticated.serverOwner !== current.subject) fail('PRIMARY_LOGIN_REJECTED');
                current = await advance(plan, current, { phase: 'VERIFIED', result: 'PASS' });
            } catch (error) {
                if (error instanceof DriverFault && ['PRIMARY_JOURNAL_CONFLICT', 'PRIMARY_JOURNAL_UNAVAILABLE'].includes(error.message)) throw error;
                // A lost confirmation/login response or observation deadline is
                // not proof that the remote mutation stopped. Keep its durable
                // intent and known subject for fenced, read-only recovery; do
                // not race a possibly active writer with destructive cleanup.
                if (error instanceof DriverFault && error.message === 'PRIMARY_PORT_UNKNOWN'
                    && ['CONFIRM_INTENT', 'LOGIN_INTENT'].includes(current.phase)) return primarySignupReport(current);
                // FAIL describes this journey, independent of cleanup's final status.
            }
            return primarySignupReport(await cleanup(plan, current));
        },
        async recover(input) {
            const plan = checkedPlan(input);
            const current = await load(plan);
            if (current.phase === 'CLEAN' || current.phase === 'PREPARED' || !current.subject) return primarySignupReport(current);
            // An intent may still have an in-flight writer. Only readback is safe;
            // no takeover/replay/delete retry is granted by elapsed time.
            if (current.deleteAttempts || ['CONFIRM_INTENT', 'LOGIN_INTENT'].includes(current.phase)) {
                await context(plan);
                await lease(plan, current.lease);
                const found = await lookup(plan, current);
                return primarySignupReport(found.status === 'ABSENT'
                    ? await advance(plan, current, { phase: 'CLEAN', cleanup: 'CLEAN' }) : current);
            }
            // A crash between confirmed transitions cannot prove the old runner is
            // idle. The installed execution owner must be fenced before recovery.
            return primarySignupReport(current);
        }
    });
}

export function verifyPrimarySignupSetup(setup) {
    const expected = {
        schemaVersion: 1, enabled: false, target: PRIMARY_SIGNUP_TARGET,
        limits: { signupAttempts: 1, mailReads: 3, confirmationAttempts: 1, loginAttempts: 1, deleteAttempts: 1, requestTimeoutMs: 30000, modelCalls: 0 },
        installation: 'UNKNOWN', journal: 'PRIVATE_DURABLE_CAS_REQUIRED', cleanup: 'IMMUTABLE_SUBJECT_AND_PARTIAL_FAILURE_PROOF_REQUIRED',
        adapter: 'NOT_INSTALLED', passwordPolicy: 'PRESERVE_MIN8_ALL_CLASSES', publicSignup: 'PRESERVE_VERIFICATION'
    };
    const canonical = value => value && typeof value === 'object' && !Array.isArray(value)
        ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value;
    if (JSON.stringify(canonical(setup)) !== JSON.stringify(canonical(expected))) fail('PRIMARY_SETUP_REJECTED');
    return { configuration: 'PASS', execution: 'NOT_STARTED', installation: 'UNKNOWN' };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    // The only CLI is an offline configuration check. No AWS/mail/auth port,
    // credential discovery, signup or deployment is reachable from this entry.
    if (process.argv.length !== 4 || process.argv[2] !== 'check-setup') fail('PRIMARY_OFFLINE_COMMAND_REQUIRED');
    process.stdout.write(JSON.stringify(verifyPrimarySignupSetup(JSON.parse(readFileSync(process.argv[3], 'utf8')))) + '\n');
}
