import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { describe, expect, test } from 'vitest';
// @ts-expect-error JavaScript runner boundary is exercised directly without AWS calls.
import { validateTarget, validateReceipt, validateWorkload, safeResults, qualificationReport, REQUIRED_TESTS } from '../../scripts/live-qa/runner-core.mjs';
const target={Account:'092954139775',Region:'us-east-1',SourceCommit:'a'.repeat(40),ApiUrl:'https://qabuild.execute-api.us-east-1.amazonaws.com',FrontendUrl:'https://main.qabuild.amplifyapp.com/',PoolId:'us-east-1_QaPool',ParticipantClientId:'pc',DisplayClientId:'dc',CognitoDomain:'https://known-enough-qa-092954139775.auth.us-east-1.amazoncognito.com',ApiFunction:'known-enough-qa-api',BrokerFunction:'known-enough-qa-fixtures',DecisionTable:'KnownEnoughQaDecisions',GroupTable:'KnownEnoughQaGroups',ControlTable:'KnownEnoughQaControl',MailboxBucket:'qa-mail',LoginSecret:'arn:aws:secretsmanager:us-east-1:092954139775:secret:known-enough/qa/run-login-secret',TestRoleArn:'arn:aws:iam::092954139775:role/KnownEnoughGithubQaTest',ReleaseRoleArn:'arn:aws:iam::092954139775:role/KnownEnoughGithubQaRelease',AmplifyAppId:'qaapp'};
const receipt={schemaVersion:1,sourceCommit:target.SourceCommit,targetApi:target.ApiUrl,targetFrontend:target.FrontendUrl,workflowRunId:'12',jobId:'34',artifacts:Object.fromEntries(['api','broker','web'].map(k=>[k,{sha256:'b'.repeat(64)}]))};
describe('LIVE02 runner preparation, no service simulation counted as live',()=>{
 test('rejects primary tables, personal profiles and untrusted target URLs',()=>{expect(validateTarget(target).GroupTable).toBe('KnownEnoughQaGroups');for(const change of [{PoolId:'us-east-1_V9OMjd0zx'},{ApiUrl:'https://u94iyvt6p9.execute-api.us-east-1.amazonaws.com'},{GroupTable:'KnownEnoughGroupsStage'},{FrontendUrl:'https://attacker.invalid/'}])expect(()=>validateTarget({...target,...change})).toThrow();const identity={Account:target.Account,Arn:'arn:aws:sts::092954139775:assumed-role/KnownEnoughGithubQaTest/run'};expect(()=>validateWorkload(identity,'A-personal')).toThrow();expect(()=>validateWorkload({...identity,Arn:'arn:aws:iam::092954139775:user/A'})).toThrow();expect(()=>validateWorkload(identity,undefined)).not.toThrow();});
 test('requires independent exact source and artifact receipt',()=>{expect(validateReceipt(target,receipt,target.SourceCommit)).toEqual(receipt);for(const r of [{...receipt,sourceCommit:'c'.repeat(40)},{...receipt,targetApi:'https://observed.invalid'},{...receipt,artifacts:{}},{...receipt,workflowRunId:'untrusted'}])expect(()=>validateReceipt(target,r,target.SourceCommit)).toThrow();});
 test('missing, duplicated, skipped or failed required tests cannot pass',()=>{const pass=REQUIRED_TESTS.map((title:string)=>({title,status:'passed'}));expect(safeResults(pass).every((r:{status:string})=>r.status==='PASS')).toBe(true);for(const tests of [pass.slice(1),[...pass,pass[0]],pass.map((t:{title:string})=>({...t,status:'skipped'})),pass.map((t:{title:string})=>({...t,status:'failed'}))])expect(safeResults(tests).every((r:{status:string})=>r.status==='PASS')).toBe(false);});
 test('whole qualification requires model signup privacy and clean cleanup',()=>{const good={processExitCode:0,processSignal:null,reportStatus:'passed',globalErrors:0,failedTests:0,runId:'run-12345',sourceCommit:target.SourceCommit,preflight:'PASS',fixtures:'PASS',tests:REQUIRED_TESTS.map((title:string)=>({title,status:'passed'})),attempts:4,signupMessages:1,privacy:'PASS',cleanup:'CLEAN'};expect(qualificationReport(good).status).toBe('PASS');for(const change of [{attempts:0},{signupMessages:0},{privacy:'BLOCKED'},{cleanup:'CLEANUP_FAILED'},{preflight:'BLOCKED'}])expect(qualificationReport({...good,...change}).status).toBe('BLOCKED_OR_FAILED');expect(JSON.stringify(qualificationReport({...good,password:'PRIVATE',errors:['SECRET'],tests:[{title:'PRIVATE_EMAIL',status:'failed'}]}))).not.toMatch(/PRIVATE|SECRET/);});
 test('absent setup produces a sanitized blocked report and makes no AWS request',()=>{const dir=mkdtempSync(resolve(tmpdir(),'ke-qa-uninstalled-'));try{const result=spawnSync(process.execPath,['scripts/live-qa/runner.mjs',dir+'/missing.json',dir+'/receipt.json','run-12345',dir+'/report.json'],{encoding:'utf8',env:{...process.env,AWS_PROFILE:'NEVER_USE_PERSONAL'}});expect(result.status).toBe(1);const report=JSON.parse(readFileSync(dir+'/report.json','utf8'));expect(report.status).toBe('BLOCKED_OR_FAILED');expect(report.counts.passed).toBe(0);expect(result.stdout).not.toMatch(/PRIVATE|NEVER_USE_PERSONAL|SECRET/);}finally{rmSync(dir,{recursive:true,force:true});}});
 test('reporter never publishes assertion errors, traces, attachments or private messages',async()=>{const dir=mkdtempSync(resolve(tmpdir(),'ke-qa-reporter-'));const before=process.env.QA_RESULTS_FILE;process.env.QA_RESULTS_FILE=dir+'/tests.json';try{
   // @ts-expect-error Reporter JavaScript deliberately accepts only title and status.
   const {default:Reporter}=await import('../../scripts/live-qa/sanitized-reporter.mjs');const reporter=new Reporter();reporter.onTestEnd({title:REQUIRED_TESTS[0],attachments:[{body:'PRIVATE'}]},{status:'failed',error:{message:'SECRET_TOKEN'},stdout:['PRIVATE_EMAIL']});reporter.onEnd({status:'failed'});expect(readFileSync(process.env.QA_RESULTS_FILE,'utf8')).not.toMatch(/PRIVATE|SECRET/);writeFileSync(dir+'/empty','');
 }finally{if(before===undefined)delete process.env.QA_RESULTS_FILE;else process.env.QA_RESULTS_FILE=before;rmSync(dir,{recursive:true,force:true});}});
});


test('failed signup phase survives the sanitized reporter and report without assertion values', async () => {
  const dir=mkdtempSync(resolve(tmpdir(),'ke-qa-phase-'));const before=process.env.QA_RESULTS_FILE;process.env.QA_RESULTS_FILE=dir+'/tests.json';
  try {
    // @ts-expect-error JavaScript reporter accepts only allowlisted phase/title/status.
    const {default:Reporter}=await import('../../scripts/live-qa/sanitized-reporter.mjs');const reporter=new Reporter();
    reporter.onStepEnd({title:REQUIRED_TESTS[0]}, {}, {title:'PRIVATE_EMAIL',error:{message:'PASSWORD'}});
    reporter.onStepEnd({title:REQUIRED_TESTS[0]}, {}, {title:'QA01_EMAIL',error:{message:'PRIVATE_EMAIL_PASSWORD'}});
    reporter.onTestEnd({title:REQUIRED_TESTS[0],annotations:[{type:'qa-mail-status',description:'MAIL_EMPTY'},{type:'qa-mail-status',description:'PRIVATE_EMAIL_PASSWORD'}]}, {status:'failed',error:{message:'SECRET'}});reporter.onEnd({status:'failed'});
    const raw=readFileSync(process.env.QA_RESULTS_FILE,'utf8');expect(raw).not.toMatch(/PRIVATE|PASSWORD|SECRET/);
    const report=qualificationReport({runId:'run-12345',tests:JSON.parse(raw).tests});expect(report.tests[0]).toMatchObject({status:'FAIL',phase:'QA01_EMAIL',mailStatus:'MAIL_EMPTY'});
    expect(safeResults([{title:REQUIRED_TESTS[0],status:'failed',phase:'PRIVATE_EMAIL',mailStatus:'PRIVATE_EMAIL'}])[0]).not.toHaveProperty('phase');
  } finally {if(before===undefined)delete process.env.QA_RESULTS_FILE;else process.env.QA_RESULTS_FILE=before;rmSync(dir,{recursive:true,force:true});}
});
