import { readFileSync } from 'node:fs';
import { describe, expect, test } from 'vitest';
// @ts-expect-error Node-only provenance is locally verified without a GitHub request.
import { trustedSource } from '../../scripts/live-qa/provenance.mjs';
// @ts-expect-error JavaScript deployment guards; no AWS service is invoked here.
import { assertCleanLease, assertInstalledEnvelope, primaryCodeGuard } from '../../scripts/live-qa/release.mjs';
// @ts-expect-error JavaScript public receipt validation is exercised directly.
import { validFiles } from '../../scripts/live-qa/public.mjs';
// @ts-expect-error Sanitized comparison against an unchanged inspector interface.
import { compareMetadata } from '../../scripts/live-qa/metadata.mjs';
// @ts-expect-error Sanitized report classification is exercised directly.
import { completeReport } from '../../scripts/live-qa/report.mjs';
// @ts-expect-error Renderer is covered by LIVE01 setup tests as well.
import { renderTemplates } from '../../scripts/live-qa/template.mjs';
const sha='a'.repeat(40);const context={repository:'Known-Enough/known-enough',ref:'refs/heads/main',sha};
const event={workflow_run:{name:'Deploy Known Enough staging to AWS Amplify',conclusion:'success',head_branch:'main',event:'push',repository:{id:1377587215,full_name:context.repository},head_repository:{id:1377587215,full_name:context.repository},head_sha:sha,id:12,workflow_id:34}};
describe('LIVE03 preparation, no GitHub dispatch/AWS operation',()=>{
 test('accepts only trusted main manual or exact successful upstream source',()=>{expect(trustedSource({},'workflow_dispatch',context)).toBe(sha);expect(trustedSource(event,'workflow_run',context)).toBe(sha);for(const change of [{conclusion:'failure'},{event:'pull_request'},{head_branch:'feature'},{head_sha:'b'.repeat(40)},{head_repository:{id:12,full_name:'attacker/fork'}},{name:'Untrusted workflow'}])expect(()=>trustedSource({workflow_run:{...event.workflow_run,...change}},'workflow_run',context)).toThrow();expect(()=>trustedSource({},'workflow_dispatch',{...context,ref:'refs/pull/1/merge'})).toThrow();});
 test('refuses expired authorization or any unfinished lease before deployment',()=>{expect(()=>assertCleanLease({payload:{S:JSON.stringify({status:'CLEANUP_FAILED'})}})).toThrow();expect(()=>assertCleanLease({payload:{S:JSON.stringify({status:'ACTIVE'})}})).toThrow();expect(()=>assertCleanLease(null)).not.toThrow();expect(()=>assertInstalledEnvelope({approved:true,expiresAt:'2026-10-02T00:00:00Z'},Date.parse('2026-10-01T00:00:00Z'))).not.toThrow();expect(()=>assertInstalledEnvelope({approved:true,expiresAt:'2026-09-30T00:00:00Z'},Date.parse('2026-10-01T00:00:00Z'))).toThrow();expect(()=>assertInstalledEnvelope({approved:false,expiresAt:'2026-10-02T00:00:00Z'})).toThrow();});
 test('primary code deployment cannot restore a paid or unconfigured runtime',()=>{const current={State:'Active',LastUpdateStatus:'Successful',Handler:'api.handler',Environment:{Variables:{KE14_MODEL_MODE:'DISABLED',KE14_PAID_CALLS_APPROVED:'false',NP_GROUPS_ENABLED:'true',NP_GROUP_TABLE_NAME:'KnownEnoughGroupsStage'}}};expect(()=>primaryCodeGuard(current)).not.toThrow();for(const change of [{KE14_MODEL_MODE:'BEDROCK'},{KE14_PAID_CALLS_APPROVED:'true'},{NP_GROUP_TABLE_NAME:'KnownEnoughQaGroups'}])expect(()=>primaryCodeGuard({...current,Environment:{Variables:{...current.Environment.Variables,...change}}})).toThrow();});
 test('public receipt rejects traversal, external URLs and absent independent index hash',()=>{expect(validFiles([{path:'/',sha256:sha+'b'.repeat(24)},{path:'/assets/app.js',sha256:'c'.repeat(64)}])).toHaveLength(2);for(const path of ['/../../secret','https://attacker.invalid/a.js','/private.json'])expect(()=>validFiles([{path:'/',sha256:'b'.repeat(64)},{path,sha256:'b'.repeat(64)}])).toThrow();expect(()=>validFiles([])).toThrow();});
 test('a complete report cannot pass a missing, stale or failed required lane',()=>{const report={sourceCommit:sha,status:'PASS',counts:{passed:7,modelAttempts:10,privateToken:'SECRET'}};const input={receipt:report,primaryRelease:report,public:report,metadata:report,qa:report};const c={sourceCommit:sha,actor:'Battosai1806',latestMain:sha,jobResults:Object.fromEntries(['provenance','release','primary-release','public','metadata','journey'].map(k=>[k,'success']))};expect(completeReport(input,c).status).toBe('PASS');for(const key of ['receipt','primaryRelease','public','metadata','qa'])expect(completeReport({...input,[key]:null},c).status).toBe('BLOCKED_OR_FAILED');expect(completeReport(input,{...c,jobResults:{...c.jobResults,journey:'failure'}}).status).toBe('BLOCKED_OR_FAILED');expect(completeReport(input,{...c,latestMain:'b'.repeat(40)}).status).toBe('BLOCKED_OR_FAILED');expect(JSON.stringify(completeReport(input,{...c,actor:'PRIVATE_EMAIL@example.org'}))).not.toMatch(/SECRET|PRIVATE_EMAIL|privateToken/);});
 test('primary comparison does not accept arbitrary observed code or expose environment secrets',()=>{const receipt={sourceCommit:sha,primary:{backendSha256:'b'.repeat(64)}};const report=compareMetadata(receipt,{collection:{status:'passed'},lambda:{codeSha256Hex:'c'.repeat(64)}},{NP_GROUP_EMAIL_KEY:'SECRET'});expect(report.status).toBe('BLOCKED_OR_FAILED');expect(JSON.stringify(report)).not.toContain('SECRET');});
 test('all workflow actions are pinned and credential jobs are separate; final report runs after failures',()=>{const workflow=readFileSync('.github/workflows/live-qa-release-and-check.yml','utf8');const actions=[...workflow.matchAll(/uses: ([^\s]+)/g)].map(match=>match[1]);expect(actions.length).toBeGreaterThan(10);for(const action of actions)expect(action).toMatch(/@[a-f0-9]{40}$/);expect(workflow).toContain('cancel-in-progress: false');expect(workflow).toContain('role-duration-seconds: 3600');expect(workflow).not.toContain('continue-on-error: true');expect(workflow).not.toContain('pull_request_target:');expect(workflow).toContain('report:\n    if: always()');expect(workflow).toContain('LIVE_QA_ENABLED');expect(workflow).not.toMatch(/AWS_PROFILE|known-enough-staging-ro/);});
 test('optional primary publication role has no config, IAM, identity or data write authority',()=>{const base=JSON.parse(readFileSync('infra/live-qa/config.example.json','utf8'));const c={...base,sourceCommit:sha,mailDomain:'qa.example.org',hostedZoneId:'Z123456789',primaryRollout:true,primaryExpectedRevision:'a'.repeat(8)+'-'+('b'.repeat(4)+'-').repeat(3)+'c'.repeat(12)};const {core}=renderTemplates(c,{apiKey:'b'.repeat(64)+'/api.zip',brokerKey:'c'.repeat(64)+'/broker.zip'});const role=JSON.stringify(core.Resources.PrimaryReleaseRole.Properties.Policies);expect(role).toContain('known-enough-stage-api');expect(role).not.toMatch(/UpdateFunctionConfiguration|iam:|cognito-idp:|dynamodb:PutItem|dynamodb:UpdateItem|s3:PutObject/);expect(role).toContain('dynamodb:GetItem');expect(role).toContain('AUTH');expect(role).toContain('LEASE');});
});
