import { createServer } from 'node:http';
import { afterEach, expect, it, vi } from 'vitest';
import { createLifecycleOwnerHandler, type LifecycleOwnerPort } from './partition-lifecycle-http.ts';
const cleanups: (() => Promise<void>)[] = [];
afterEach(async () => { await Promise.all(cleanups.splice(0).map(close => close())); });
const hash = 'a'.repeat(64); const principal = { kind: 'participant' as const, subject: 'signed-owner' };
async function fixture(actor: typeof principal | { kind: 'display'; subject: string; roomId: string } | null = principal, timeoutMs = 1000) {
 const port = { exportOwn: vi.fn(async () => ({ own: 'private-owned-export' })), loadOwnPlan: vi.fn(async () => ({ bytes: Buffer.from('SERVER_ONLY_SEAL'), expected: { opId: 'owned-op', planHash: hash } })), consent: vi.fn(async (_bytes: Buffer, _expected: { opId: string; planHash: string }, _principal: unknown, expiresAt: string, revoked: boolean) => ({ opId: 'owned-op', granted: !revoked, expiresAt })), status: vi.fn(async () => ({ state: 'ERASING', nextStep: 1, totalSteps: 3 })) };
 const fallback = vi.fn((_, response) => { response.statusCode = 404; response.end(); });
 const server = createServer(createLifecycleOwnerHandler({ owner: port as LifecycleOwnerPort, authenticate: async () => actor, allowedOrigin: 'https://app.example.invalid', fallback, timeoutMs, maxConcurrent: 1 }));
 await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); const address = server.address(); if (!address || typeof address === 'string') throw new Error();
 cleanups.push(() => new Promise<void>(resolve => { server.closeAllConnections(); server.close(() => resolve()); }));
 const call = (path: string, body?: unknown, origin?: string) => fetch(`http://127.0.0.1:${address.port}${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { ...(body === undefined ? {} : { 'content-type': 'application/json' }), ...(origin ? { origin } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
 return { port, call, fallback };
}
it.each([null, { kind: 'display' as const, subject: 'display', roomId: 'room' }])('export requires verified participant, never display/body identity: %j', async actor => { const f = await fixture(actor); expect((await f.call('/account/export')).status).toBe(403); expect(f.port.exportOwn).not.toHaveBeenCalled(); });
it('export uses signed owner only and prevents cache storage or arbitrary subject selectors', async () => { const f = await fixture(); const response = await f.call('/account/export'); expect(await response.json()).toEqual({ own: 'private-owned-export' }); expect(response.headers.get('cache-control')).toBe('no-store'); expect(f.port.exportOwn).toHaveBeenCalledWith(principal); expect((await f.call('/account/export?subject=other')).status).toBe(422); });
it('consent uses server-held sealed plan; extra subject/sealed bytes or stale plan hashes cannot authorize it', async () => { const f = await fixture(); const body = { planHash: hash, expiresAt: '2026-10-11T00:00:00Z', revoked: false }; expect((await f.call('/account/erasure/owned-op/consent', { ...body, subject: 'other' })).status).toBe(422); expect(f.port.loadOwnPlan).not.toHaveBeenCalled(); expect((await f.call('/account/erasure/owned-op/consent', { ...body, planHash: 'b'.repeat(64) })).status).toBe(409); expect(f.port.consent).not.toHaveBeenCalled(); expect((await f.call('/account/erasure/owned-op/consent', body)).status).toBe(200); expect(f.port.consent).toHaveBeenCalledWith(Buffer.from('SERVER_ONLY_SEAL'), { opId: 'owned-op', planHash: hash }, principal, body.expiresAt, false); });
it('owner revocation is forwarded and only coarse progress is returned, without sealed plan bytes', async () => { const f = await fixture(); await f.call('/account/erasure/owned-op/consent', { planHash: hash, expiresAt: '2026-10-11T00:00:00Z', revoked: true }); expect(f.port.consent.mock.calls[0]?.at(-1)).toBe(true); const text = await (await f.call('/account/erasure/owned-op')).text(); expect(text).toContain('ERASING'); expect(text).not.toContain('SERVER_ONLY_SEAL'); });
it('foreign origin and oversized command fail before consent; private storage errors stay sanitized', async () => { const f = await fixture(); expect((await f.call('/account/export', undefined, 'https://other.example.invalid')).status).toBe(403); expect((await f.call('/account/erasure/owned-op/consent', { excess: 'x'.repeat(3000) })).status).toBe(422); f.port.exportOwn.mockRejectedValueOnce(new Error('PRIVATE_EMAIL TOKEN')); const response = await f.call('/account/export'); expect(response.status).toBe(503); expect(await response.text()).not.toMatch(/PRIVATE|TOKEN/); });
it('a timed-out unresolved owner call keeps its concurrency slot until actual settlement', async () => { const f = await fixture(principal, 30); let release!: () => void; f.port.exportOwn.mockImplementationOnce(() => new Promise(resolve => { release = () => resolve({ own: 'private-owned-export' }); })); expect((await f.call('/account/export')).status).toBe(503); expect((await f.call('/account/export')).status).toBe(503); expect(f.port.exportOwn).toHaveBeenCalledTimes(1); release(); await new Promise(resolve => setTimeout(resolve, 10)); expect((await f.call('/account/export')).status).toBe(200); });
it('unknown owner erasure paths fail closed instead of exposing operator prepare or executor functions', async () => { const f = await fixture(); expect((await f.call('/account/erasure/owned-op/execute', {})).status).toBe(404); expect(f.fallback).not.toHaveBeenCalled(); expect((await f.call('/groups')).status).toBe(404); expect(f.fallback).toHaveBeenCalledOnce(); });

it('private additions to coarse progress are rejected rather than accidentally published', async () => {
 const f = await fixture(); f.port.status.mockResolvedValueOnce({ state: 'ERASING', nextStep: 1, totalSteps: 3, privateSubjects: ['PRIVATE_SUBJECT'] } as never);
 const response = await f.call('/account/erasure/owned-op'); expect(response.status).toBe(503); expect(await response.text()).not.toContain('PRIVATE');
});
